### ISSUE TITLE
how to force yolo on GPU

### ISSUE THREAD

**Issue by Blindsp0t-creative** [mbaske/yolo-unity#2]
Hi, 
Thank you so much for your work on integrating Yolo in Unity!

I just can't find a way to force the Yolo server to work on my GPU, could you please point me what i have to do... ?

For now i followed Alturos.Yolo instructions on GPU:

> GPU requirements (optional)

    Install the latest Nvidia driver for your graphic device
    Install Nvidia CUDA Toolkit 10.0 (must be installed add a hardware driver for cuda support)
    Download Nvidia cuDNN v7.4.2.24 for CUDA 10.0
    Copy the cudnn64_7.dll from the output directory of point 2. into the x64 folder of your project.

Maybe i don't put the cudnn64_7.dll at the right place ... ?

Thanks again.

**Comment by mbaske** [comment]
Hi @Blindsp0t-creative - Sorry, I'm not sure how to solve this. I don't have a Nvidia GPU right now. So far, I've only run Yolo on my CPU.
