### ISSUE TITLE
how to change weights to YOLOv3-tiny to YOLOv3?(pertrained dataset)

### ISSUE THREAD

**Issue by UEDEVLabs** [mbaske/yolo-unity#4]
@mbaske can u help me to change weights to YOLOv3?
Thanks!

**Comment by mbaske** [comment]
Please add v3 files to
/YoloPretrained
and update the Config links in
/YoloSrc/Alturos.Yolo/Alturos.Yolo.csproj
lines 84 - 93

/YoloSrc/Alturos.Yolo/ConfigurationDetector.cs is looking for .names, .cfg and .weights files in @".\Config"

**Comment by UEDEVLabs** [comment]
@mbaske Thanks lot
