### ISSUE TITLE
I have troubles on compiling this.

### ISSUE THREAD

**Issue by TKTim** [mbaske/yolo-unity#7]
When I compile it in Unity it works perfectly.
![image](https://user-images.githubusercontent.com/36975354/76840607-73685800-6872-11ea-882f-670694f233d7.png)

But when I try to build it in Android, it does this.
![image](https://user-images.githubusercontent.com/36975354/76840873-dce86680-6872-11ea-81d7-11e09007c1b0.png)

It seems like it can't define the codes of Grpc

**Comment by mbaske** [comment]
Maybe android needs a different gRPC plugin? I'm just guessing here, haven't tested this on android myself yet.

**Comment by TKTim** [comment]
Thanks
