### ISSUE TITLE
Can you tell me where is the code you use to send DetectionResult back to Unity?

### ISSUE THREAD

**Issue by TKTim** [mbaske/yolo-unity#8]
Like the title , it will be super helpful, Thx

**Comment by mbaske** [comment]
That's handled here:
https://github.com/mbaske/yolo-unity/blob/master/YoloSrc/YoloServer/Program.cs
https://github.com/mbaske/yolo-unity/blob/master/YoloSrc/YoloServer/YoloServiceImpl.cs

**Comment by TKTim** [comment]
await responseStream.WriteAsync(response); 
Is this one?
